name: chat_demo_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # For integrating firebase
  firebase_core: ^2.2.0

  # For handling firebase authentication
  firebase_auth: ^4.1.3

  # For handling google sign in
  google_sign_in: ^5.4.2

  # For accessing cloud firestore database
  cloud_firestore: ^4.1.0

  # For showing network images
  cached_network_image: ^3.2.3

  # For picking images
  image_picker: ^0.8.6

  # For accessing Firebase Storage (for uploading files)
  firebase_storage: ^11.0.6

  # For showing Emojis
  emoji_picker_flutter: ^1.5.1

  # For accessing firebase messaging (Push Notification)
  firebase_messaging: ^14.2.0

  # For calling RestAPIs
  http: ^0.13.5

  # For creating notification channel
  flutter_notification_channel: ^2.0.0

  # For storing images into gallery
  gallery_saver: ^2.3.2
  flutter_svg: ^2.0.9
  google_fonts: ^4.0.4
  simple_gradient_text: ^1.3.0
  gradient_borders: ^1.0.0
  get: ^4.6.6
  flashy_tab_bar2: ^0.0.6

  #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/chat.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
#  web:
#    generate: true
#    image_path: "path/to/image.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "path/to/image.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "path/to/image.png"

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
